; generated by weavec
; source: test/performance/wir/0023_mod_i32.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %.t0 = srem i32 42, 10
  ret i32 %.t0
}

