; generated by weavec
; source: test/performance/wir/0048_string_escape.wir
; core-version: 2

; declarations

declare i32 @puts(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  ret i32 42
}

