; generated by weavec
; source: test/performance/wir/0055_integration_nested_control_flow.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %sum.addr = alloca i64
  %i.addr = alloca i64
  ; let sum
  store i64 0, ptr %sum.addr
  ; let i
  store i64 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i64, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i64 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i64 %i.phi0, 10
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = icmp sgt i64 %i.phi0, 5
  br i1 %t1, label %then1, label %else1
then1:
  ; then
  ; set sum
  %t2 = load i64, ptr %sum.addr
  %t3 = mul i64 %i.phi0, 2
  %t4 = add i64 %t2, %t3
  store i64 %t4, ptr %sum.addr
  br label %endif1
else1:
  ; else
  ; set sum
  %t5 = load i64, ptr %sum.addr
  %t6 = add i64 %t5, %i.phi0
  store i64 %t6, ptr %sum.addr
  br label %endif1
endif1:
  ; set i
  %i.next0 = add i64 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i64 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t7 = load i64, ptr %sum.addr
  %t8 = trunc i64 %t7 to i32
  ret i32 %t8
}

