; generated by weavec
; source: test/performance/wir/0070_horner_polynomial_i32.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @horner3(i32 3)
  %t1 = sub i32 %t0, 11
  ret i32 %t1
}

; function: horner3
; params: i32
; returns: i32
define i32 @horner3(i32 %x) {
entry:
  %acc.addr = alloca i32
  %i.addr = alloca i32
  ; let acc
  store i32 1, ptr %acc.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 3
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i32, ptr %acc.addr
  %t3 = mul i32 %t2, %x
  %t4 = add i32 %t3, 2
  ; let next
  ; set acc
  store i32 %t4, ptr %acc.addr
  ; set i
  %t5 = load i32, ptr %i.addr
  %t6 = add i32 %t5, 1
  store i32 %t6, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t7 = load i32, ptr %acc.addr
  ret i32 %t7
}

