; generated by weavec2
; source: test/performance/wir/0071_collatz_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @collatz_steps(i32 13)
  %t1 = add i32 %t0, 33
  ret i32 %t1
}

; function: collatz_steps
; params: i32
; returns: i32
define i32 @collatz_steps(i32 %start) {
entry:
  %n.addr = alloca i32
  %steps.addr = alloca i32
  ; let n
  store i32 %start, ptr %n.addr
  ; let steps
  store i32 0, ptr %steps.addr
  ; while condition
  br label %while.pre
while.pre:
  %steps.init0 = load i32, ptr %steps.addr
  br label %while.cond
while.cond:
  %steps.phi0 = phi i32 [%steps.init0, %while.pre], [%steps.next0, %while.latch]
  %t0 = load i32, ptr %n.addr
  %t1 = icmp ne i32 %t0, 1
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t2 = load i32, ptr %n.addr
  %t3 = srem i32 %t2, 2
  %t4 = icmp eq i32 %t3, 0
  br i1 %t4, label %then1, label %else1
then1:
  ; then
  ; set n
  %t5 = load i32, ptr %n.addr
  %t6 = sdiv i32 %t5, 2
  store i32 %t6, ptr %n.addr
  br label %endif1
else1:
  ; else
  ; set n
  %t7 = load i32, ptr %n.addr
  %t8 = mul i32 %t7, 3
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %n.addr
  br label %endif1
endif1:
  ; set steps
  %steps.next0 = add i32 %steps.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %steps.phi0, ptr %steps.addr
  br label %while.end
while.end:
  ; return
  %t10 = load i32, ptr %steps.addr
  ret i32 %t10
}

