; generated by weavec
; source: test/performance/wir/0072_pow_square_i32.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @pow_i32(i32 3, i32 3)
  %t1 = add i32 %t0, 15
  ret i32 %t1
}

; function: pow_i32
; params: i32, i32
; returns: i32
define i32 @pow_i32(i32 %base0, i32 %exp0) {
entry:
  %result.addr = alloca i32
  %base.addr = alloca i32
  %exp.addr = alloca i32
  ; let result
  store i32 1, ptr %result.addr
  ; let base
  store i32 %base0, ptr %base.addr
  ; let exp
  store i32 %exp0, ptr %exp.addr
  ; while condition
  br label %while.pre
while.pre:
  %base.init0 = load i32, ptr %base.addr
  %exp.init0 = load i32, ptr %exp.addr
  br label %while.cond
while.cond:
  %base.phi0 = phi i32 [%base.init0, %while.pre], [%base.next0, %while.latch]
  %exp.phi0 = phi i32 [%exp.init0, %while.pre], [%exp.next0, %while.latch]
  %t0 = icmp sgt i32 %exp.phi0, 0
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %exp.phi0, 2
  %t2 = icmp ne i32 %t1, 0
  br i1 %t2, label %then1, label %endif1
then1:
  ; then
  ; set result
  %t3 = load i32, ptr %result.addr
  %t4 = mul i32 %t3, %base.phi0
  store i32 %t4, ptr %result.addr
  br label %endif1
endif1:
  ; set base
  %base.next0 = mul i32 %base.phi0, %base.phi0
  ; set exp
  %exp.next0 = sdiv i32 %exp.phi0, 2
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %base.phi0, ptr %base.addr
  store i32 %exp.phi0, ptr %exp.addr
  br label %while.end
while.end:
  ; return
  %t5 = load i32, ptr %result.addr
  ret i32 %t5
}

