; generated by weavec
; source: test/performance/wir/0084_count_divisors_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @count_divisors(i32 36)
  ret i32 %t0
}

; function: count_divisors
; params: i32
; returns: i32
define i32 @count_divisors(i32 %n) {
entry:
  %d.addr = alloca i32
  %count.addr = alloca i32
  ; let d
  store i32 1, ptr %d.addr
  ; let count
  store i32 0, ptr %count.addr
  ; while condition
  br label %while.pre
while.pre:
  %d.init0 = load i32, ptr %d.addr
  br label %while.cond
while.cond:
  %d.phi0 = phi i32 [%d.init0, %while.pre], [%d.next0, %while.latch]
  %t0 = mul i32 %d.phi0, %d.phi0
  %t1 = icmp sle i32 %t0, %n
  br i1 %t1, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t2 = srem i32 %n, %d.phi0
  %t3 = icmp eq i32 %t2, 0
  br i1 %t3, label %then1, label %endif1
then1:
  ; then
  ; set count
  %t4 = load i32, ptr %count.addr
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr %count.addr
  br label %endif1
endif1:
  ; set d
  %d.next0 = add i32 %d.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %d.phi0, ptr %d.addr
  br label %while.end
while.end:
  ; return
  %t6 = load i32, ptr %count.addr
  ret i32 %t6
}

