; generated by weavec
; source: test/performance/wir/0085_is_prime_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @is_prime(i32 97)
  ret i32 %t0
}

; function: is_prime
; params: i32
; returns: i32
define i32 @is_prime(i32 %n) {
entry:
  %d.addr = alloca i32
  %prime.addr = alloca i32
  ; if condition
  %t0 = icmp sle i32 %n, 1
  br i1 %t0, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  ; let d
  store i32 2, ptr %d.addr
  ; let prime
  store i32 1, ptr %prime.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %d.init1 = load i32, ptr %d.addr
  br label %while.cond1
while.cond1:
  %d.phi1 = phi i32 [%d.init1, %while.pre1], [%d.next1, %while.latch1]
  %t1 = mul i32 %d.phi1, %d.phi1
  %t2 = icmp sle i32 %t1, %n
  %t3 = load i32, ptr %prime.addr
  %t4 = icmp ne i32 %t3, 0
  %t5 = and i1 %t2, %t4
  br i1 %t5, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  ; if condition
  %t6 = srem i32 %n, %d.phi1
  %t7 = icmp eq i32 %t6, 0
  br i1 %t7, label %then2, label %endif2
then2:
  ; then
  ; set prime
  store i32 0, ptr %prime.addr
  br label %endif2
endif2:
  ; set d
  %d.next1 = add i32 %d.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %d.phi1, ptr %d.addr
  br label %while.end1
while.end1:
  ; return
  %t8 = load i32, ptr %prime.addr
  ret i32 %t8
}

