; generated by weavec
; source: test/performance/wir/0088_digital_sum_i32.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %.t0 = call i32 @digital_sum(i32 9876)
  ret i32 %.t0
}

; function: digital_sum
; params: i32
; returns: i32
define i32 @digital_sum(i32 %n) {
entry:
  %x.addr = alloca i32
  %total.addr = alloca i32
  ; let x
  store i32 %n, ptr %x.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %.t0 = load i32, ptr %x.addr
  %.t1 = icmp sgt i32 %.t0, 0
  br i1 %.t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set total
  %.t2 = load i32, ptr %total.addr
  %.t3 = load i32, ptr %x.addr
  %.t4 = srem i32 %.t3, 10
  %.t5 = add i32 %.t2, %.t4
  store i32 %.t5, ptr %total.addr
  ; set x
  %.t6 = load i32, ptr %x.addr
  %.t7 = sdiv i32 %.t6, 10
  store i32 %.t7, ptr %x.addr
  br label %while.cond
while.end:
  ; return
  %.t8 = load i32, ptr %total.addr
  ret i32 %.t8
}

