; generated by weavec2
; source: test/performance/wir/0091_linear_search5_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 -1
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 11, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 22, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 33, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 44, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 55, ptr %t6
  %t7 = call i32 @find5(ptr %t0, i32 33)
  ; let idx
  call void @free(ptr %t0)
  ; return
  ret i32 %t7
}

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: find5
; params: ptr, i32
; returns: i32
define i32 @find5(ptr %items, i32 %target) {
entry:
  %i.addr = alloca i32
  %found.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let found
  store i32 -1, ptr %found.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 5
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = call ptr @elem_ptr(ptr %items, i32 %i.phi0)
  %t2 = load i32, ptr %t1
  %t3 = icmp eq i32 %t2, %target
  %t4 = load i32, ptr %found.addr
  %t5 = icmp eq i32 %t4, -1
  %t6 = and i1 %t3, %t5
  br i1 %t6, label %then1, label %endif1
then1:
  ; then
  ; set found
  store i32 %i.phi0, ptr %found.addr
  br label %endif1
endif1:
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t7 = load i32, ptr %found.addr
  ret i32 %t7
}

