; generated by weavec
; source: test/performance/wir/0092_array_max5_i32.wir
; core-version: 3

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %.t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %.t1 = icmp eq ptr %.t0, null
  br i1 %.t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %.t2 = call ptr @elem_ptr(ptr %.t0, i32 0)
  store i32 3, ptr %.t2
  %.t3 = call ptr @elem_ptr(ptr %.t0, i32 1)
  store i32 9, ptr %.t3
  %.t4 = call ptr @elem_ptr(ptr %.t0, i32 2)
  store i32 1, ptr %.t4
  %.t5 = call ptr @elem_ptr(ptr %.t0, i32 3)
  store i32 7, ptr %.t5
  %.t6 = call ptr @elem_ptr(ptr %.t0, i32 4)
  store i32 5, ptr %.t6
  %.t7 = call i32 @max5(ptr %.t0)
  ; let m
  call void @free(ptr %.t0)
  ; return
  ret i32 %.t7
}

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %.t0 = sext i32 %index to i64
  %.t1 = getelementptr i32, ptr %base, i64 %.t0
  ret ptr %.t1
}

; function: max5
; params: ptr
; returns: i32
define i32 @max5(ptr %items) {
entry:
  %m.addr = alloca i32
  %i.addr = alloca i32
  %.t0 = call ptr @elem_ptr(ptr %items, i32 0)
  %.t1 = load i32, ptr %.t0
  ; let m
  store i32 %.t1, ptr %m.addr
  ; let i
  store i32 1, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %.t2 = load i32, ptr %i.addr
  %.t3 = icmp slt i32 %.t2, 5
  br i1 %.t3, label %while.body, label %while.end
while.body:
  ; while body
  %.t4 = load i32, ptr %i.addr
  %.t5 = call ptr @elem_ptr(ptr %items, i32 %.t4)
  %.t6 = load i32, ptr %.t5
  ; let v
  ; if condition
  %.t7 = load i32, ptr %m.addr
  %.t8 = icmp sgt i32 %.t6, %.t7
  br i1 %.t8, label %then1, label %endif1
then1:
  ; then
  ; set m
  store i32 %.t6, ptr %m.addr
  br label %endif1
endif1:
  ; set i
  %.t9 = load i32, ptr %i.addr
  %.t10 = add i32 %.t9, 1
  store i32 %.t10, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %.t11 = load i32, ptr %m.addr
  ret i32 %.t11
}

