; generated by weavec
; source: test/performance/wir/0098_sum_cubes_range_i32.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @sum_cubes(i32 4)
  ret i32 %t0
}

; function: sum_cubes
; params: i32
; returns: i32
define i32 @sum_cubes(i32 %n) {
entry:
  %i.addr = alloca i32
  %total.addr = alloca i32
  ; let i
  store i32 1, ptr %i.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, %n
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  %t2 = load i32, ptr %i.addr
  %t3 = load i32, ptr %i.addr
  %t4 = mul i32 %t2, %t3
  ; let sq
  ; set total
  %t5 = load i32, ptr %total.addr
  %t6 = load i32, ptr %i.addr
  %t7 = mul i32 %t4, %t6
  %t8 = add i32 %t5, %t7
  store i32 %t8, ptr %total.addr
  ; set i
  %t9 = load i32, ptr %i.addr
  %t10 = add i32 %t9, 1
  store i32 %t10, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t11 = load i32, ptr %total.addr
  ret i32 %t11
}

