; generated by weavec
; source: test/performance/wir/0099_is_perfect_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @is_perfect(i32 28)
  ret i32 %t0
}

; function: is_perfect
; params: i32
; returns: i32
define i32 @is_perfect(i32 %n) {
entry:
  %d.addr = alloca i32
  %sum.addr = alloca i32
  ; let d
  store i32 1, ptr %d.addr
  ; let sum
  store i32 0, ptr %sum.addr
  ; while condition
  br label %while.pre
while.pre:
  %d.init0 = load i32, ptr %d.addr
  br label %while.cond
while.cond:
  %d.phi0 = phi i32 [%d.init0, %while.pre], [%d.next0, %while.latch]
  %t0 = icmp slt i32 %d.phi0, %n
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %n, %d.phi0
  %t2 = icmp eq i32 %t1, 0
  br i1 %t2, label %then1, label %endif1
then1:
  ; then
  ; set sum
  %t3 = load i32, ptr %sum.addr
  %t4 = add i32 %t3, %d.phi0
  store i32 %t4, ptr %sum.addr
  br label %endif1
endif1:
  ; set d
  %d.next0 = add i32 %d.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %d.phi0, ptr %d.addr
  br label %while.end
while.end:
  ; if condition
  %t5 = load i32, ptr %sum.addr
  %t6 = icmp eq i32 %t5, %n
  br i1 %t6, label %then2, label %else2
then2:
  ; then
  ; return
  ret i32 1
else2:
  ; else
  ; return
  ret i32 0
}

