; generated by weavec
; source: test/performance/wir/0100_reverse_digits_i32.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @reverse_digits(i32 12034)
  ret i32 %t0
}

; function: reverse_digits
; params: i32
; returns: i32
define i32 @reverse_digits(i32 %n) {
entry:
  %x.addr = alloca i32
  %rev.addr = alloca i32
  ; let x
  store i32 %n, ptr %x.addr
  ; let rev
  store i32 0, ptr %rev.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %x.addr
  %t1 = icmp sgt i32 %t0, 0
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set rev
  %t2 = load i32, ptr %rev.addr
  %t3 = mul i32 %t2, 10
  %t4 = load i32, ptr %x.addr
  %t5 = srem i32 %t4, 10
  %t6 = add i32 %t3, %t5
  store i32 %t6, ptr %rev.addr
  ; set x
  %t7 = load i32, ptr %x.addr
  %t8 = sdiv i32 %t7, 10
  store i32 %t8, ptr %x.addr
  br label %while.cond
while.end:
  ; return
  %t9 = load i32, ptr %rev.addr
  ret i32 %t9
}

