; generated by weavec
; source: test/performance/wir/0115_sum_powers_of_two_i32.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @sum_powers(i32 5)
  ret i32 %t0
}

; function: sum_powers
; params: i32
; returns: i32
define i32 @sum_powers(i32 %k) {
entry:
  %i.addr = alloca i32
  %p.addr = alloca i32
  %total.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let p
  store i32 1, ptr %p.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, %k
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set total
  %t2 = load i32, ptr %total.addr
  %t3 = load i32, ptr %p.addr
  %t4 = add i32 %t2, %t3
  store i32 %t4, ptr %total.addr
  ; set p
  %t5 = load i32, ptr %p.addr
  %t6 = mul i32 %t5, 2
  store i32 %t6, ptr %p.addr
  ; set i
  %t7 = load i32, ptr %i.addr
  %t8 = add i32 %t7, 1
  store i32 %t8, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t9 = load i32, ptr %total.addr
  ret i32 %t9
}

