; generated by weavec2
; source: test/performance/wir/0117_multiples_sum_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @sum_multiples_below(i32 20)
  ret i32 %t0
}

; function: sum_multiples_below
; params: i32
; returns: i32
define i32 @sum_multiples_below(i32 %n) {
entry:
  %i.addr = alloca i32
  %total.addr = alloca i32
  ; let i
  store i32 1, ptr %i.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, %n
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %i.phi0, 3
  %t2 = icmp eq i32 %t1, 0
  %t3 = srem i32 %i.phi0, 5
  %t4 = icmp eq i32 %t3, 0
  %t5 = or i1 %t2, %t4
  br i1 %t5, label %then1, label %endif1
then1:
  ; then
  ; set total
  %t6 = load i32, ptr %total.addr
  %t7 = add i32 %t6, %i.phi0
  store i32 %t7, ptr %total.addr
  br label %endif1
endif1:
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t8 = load i32, ptr %total.addr
  ret i32 %t8
}

