; generated by weavec
; source: test/performance/wir/0118_bubble_sort5_i32.wir
; core-version: 3

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 5, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 1, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 4, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 2, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 3, ptr %t6
  call void @bubble_sort5(ptr %t0)
  %t7 = call ptr @elem_ptr(ptr %t0, i32 0)
  %t8 = load i32, ptr %t7
  ; let first
  call void @free(ptr %t0)
  ; return
  ret i32 %t8
}

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: bubble_sort5
; params: ptr
; returns: void
define void @bubble_sort5(ptr %items) {
entry:
  %pass.addr = alloca i32
  %j.addr = alloca i32
  ; let pass
  store i32 0, ptr %pass.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %pass.addr
  %t1 = icmp slt i32 %t0, 4
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let j
  store i32 0, ptr %j.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t2 = load i32, ptr %j.addr
  %t3 = load i32, ptr %pass.addr
  %t4 = sub i32 4, %t3
  %t5 = icmp slt i32 %t2, %t4
  br i1 %t5, label %while.body1, label %while.end1
while.body1:
  ; while body
  %t6 = load i32, ptr %j.addr
  %t7 = call ptr @elem_ptr(ptr %items, i32 %t6)
  %t8 = load i32, ptr %t7
  ; let a
  %t9 = load i32, ptr %j.addr
  %t10 = add i32 %t9, 1
  %t11 = call ptr @elem_ptr(ptr %items, i32 %t10)
  %t12 = load i32, ptr %t11
  ; let b
  ; if condition
  %t13 = icmp sgt i32 %t8, %t12
  br i1 %t13, label %then2, label %endif2
then2:
  ; then
  %t14 = load i32, ptr %j.addr
  %t15 = call ptr @elem_ptr(ptr %items, i32 %t14)
  store i32 %t12, ptr %t15
  %t16 = load i32, ptr %j.addr
  %t17 = add i32 %t16, 1
  %t18 = call ptr @elem_ptr(ptr %items, i32 %t17)
  store i32 %t8, ptr %t18
  br label %endif2
endif2:
  ; set j
  %t19 = load i32, ptr %j.addr
  %t20 = add i32 %t19, 1
  store i32 %t20, ptr %j.addr
  br label %while.cond1
while.end1:
  ; set pass
  %t21 = load i32, ptr %pass.addr
  %t22 = add i32 %t21, 1
  store i32 %t22, ptr %pass.addr
  br label %while.cond
while.end:
  ret void
}

