; generated by weavec
; source: test/performance/wir/0122_kadane5_i32.wir
; core-version: 3

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %.t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %.t1 = icmp eq ptr %.t0, null
  br i1 %.t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %.t2 = call ptr @elem_ptr(ptr %.t0, i32 0)
  store i32 -2, ptr %.t2
  %.t3 = call ptr @elem_ptr(ptr %.t0, i32 1)
  store i32 3, ptr %.t3
  %.t4 = call ptr @elem_ptr(ptr %.t0, i32 2)
  store i32 -1, ptr %.t4
  %.t5 = call ptr @elem_ptr(ptr %.t0, i32 3)
  store i32 4, ptr %.t5
  %.t6 = call ptr @elem_ptr(ptr %.t0, i32 4)
  store i32 -5, ptr %.t6
  %.t7 = call i32 @kadane5(ptr %.t0)
  ; let m
  call void @free(ptr %.t0)
  ; return
  ret i32 %.t7
}

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %.t0 = sext i32 %index to i64
  %.t1 = getelementptr i32, ptr %base, i64 %.t0
  ret ptr %.t1
}

; function: kadane5
; params: ptr
; returns: i32
define i32 @kadane5(ptr %items) {
entry:
  %i.addr = alloca i32
  %best.addr = alloca i32
  %cur.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let best
  store i32 -2147483648, ptr %best.addr
  ; let cur
  store i32 0, ptr %cur.addr
  ; while condition
  br label %while.cond
while.cond:
  %.t0 = load i32, ptr %i.addr
  %.t1 = icmp slt i32 %.t0, 5
  br i1 %.t1, label %while.body, label %while.end
while.body:
  ; while body
  %.t2 = load i32, ptr %i.addr
  %.t3 = call ptr @elem_ptr(ptr %items, i32 %.t2)
  %.t4 = load i32, ptr %.t3
  ; let v
  ; set cur
  %.t5 = load i32, ptr %cur.addr
  %.t6 = add i32 %.t5, %.t4
  store i32 %.t6, ptr %cur.addr
  ; if condition
  %.t7 = load i32, ptr %cur.addr
  %.t8 = icmp slt i32 %.t7, %.t4
  br i1 %.t8, label %then1, label %endif1
then1:
  ; then
  ; set cur
  store i32 %.t4, ptr %cur.addr
  br label %endif1
endif1:
  ; if condition
  %.t9 = load i32, ptr %cur.addr
  %.t10 = load i32, ptr %best.addr
  %.t11 = icmp sgt i32 %.t9, %.t10
  br i1 %.t11, label %then2, label %endif2
then2:
  ; then
  ; set best
  %.t12 = load i32, ptr %cur.addr
  store i32 %.t12, ptr %best.addr
  br label %endif2
endif2:
  ; set i
  %.t13 = load i32, ptr %i.addr
  %.t14 = add i32 %.t13, 1
  store i32 %.t14, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %.t15 = load i32, ptr %best.addr
  ret i32 %.t15
}

