; generated by weavec
; source: test/performance/wir/0125_all_equal5_i32.wir
; core-version: 2

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 20)
  ; let items
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem_ptr(ptr %t0, i32 0)
  store i32 7, ptr %t2
  %t3 = call ptr @elem_ptr(ptr %t0, i32 1)
  store i32 7, ptr %t3
  %t4 = call ptr @elem_ptr(ptr %t0, i32 2)
  store i32 7, ptr %t4
  %t5 = call ptr @elem_ptr(ptr %t0, i32 3)
  store i32 7, ptr %t5
  %t6 = call ptr @elem_ptr(ptr %t0, i32 4)
  store i32 7, ptr %t6
  %t7 = call i32 @all_equal5(ptr %t0)
  ; let r
  call void @free(ptr %t0)
  ; return
  ret i32 %t7
}

; function: elem_ptr
; params: ptr, i32
; returns: ptr
define ptr @elem_ptr(ptr %base, i32 %index) {
entry:
  ; return
  %t0 = sext i32 %index to i64
  %t1 = getelementptr i32, ptr %base, i64 %t0
  ret ptr %t1
}

; function: all_equal5
; params: ptr
; returns: i32
define i32 @all_equal5(ptr %items) {
entry:
  %i.addr = alloca i32
  %ok.addr = alloca i32
  %t0 = call ptr @elem_ptr(ptr %items, i32 0)
  %t1 = load i32, ptr %t0
  ; let first
  ; let i
  store i32 1, ptr %i.addr
  ; let ok
  store i32 1, ptr %ok.addr
  ; while condition
  br label %while.cond
while.cond:
  %t2 = load i32, ptr %i.addr
  %t3 = icmp slt i32 %t2, 5
  %t4 = load i32, ptr %ok.addr
  %t5 = icmp ne i32 %t4, 0
  %t6 = and i1 %t3, %t5
  br i1 %t6, label %while.body, label %while.end
while.body:
  ; while body
  ; if condition
  %t7 = load i32, ptr %i.addr
  %t8 = call ptr @elem_ptr(ptr %items, i32 %t7)
  %t9 = load i32, ptr %t8
  %t10 = icmp ne i32 %t9, %t1
  br i1 %t10, label %then1, label %endif1
then1:
  ; then
  ; set ok
  store i32 0, ptr %ok.addr
  br label %endif1
endif1:
  ; set i
  %t11 = load i32, ptr %i.addr
  %t12 = add i32 %t11, 1
  store i32 %t12, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t13 = load i32, ptr %ok.addr
  ret i32 %t13
}

