; generated by weavec2
; source: test/performance/wir/0131_loop_triple_if_carried_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @run()
  ret i32 %t0
}

; function: run
; params: none
; returns: i32
define i32 @run() {
entry:
  %a.addr = alloca i32
  %b.addr = alloca i32
  %c.addr = alloca i32
  %i.addr = alloca i32
  ; let a
  store i32 0, ptr %a.addr
  ; let b
  store i32 0, ptr %b.addr
  ; let c
  store i32 0, ptr %c.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.pre
while.pre:
  %i.init0 = load i32, ptr %i.addr
  br label %while.cond
while.cond:
  %i.phi0 = phi i32 [%i.init0, %while.pre], [%i.next0, %while.latch]
  %t0 = icmp slt i32 %i.phi0, 24
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = srem i32 %i.phi0, 3
  %t2 = icmp eq i32 %t1, 0
  br i1 %t2, label %then1, label %else1
then1:
  ; then
  ; if condition
  %t3 = srem i32 %i.phi0, 6
  %t4 = icmp eq i32 %t3, 0
  br i1 %t4, label %then2, label %else2
then2:
  ; then
  ; if condition
  %t5 = srem i32 %i.phi0, 9
  %t6 = icmp eq i32 %t5, 0
  br i1 %t6, label %then3, label %else3
then3:
  ; then
  ; set a
  %t7 = load i32, ptr %a.addr
  %t8 = add i32 %t7, 3
  store i32 %t8, ptr %a.addr
  ; set b
  %t9 = load i32, ptr %b.addr
  %t10 = add i32 %t9, 2
  store i32 %t10, ptr %b.addr
  ; set c
  %t11 = load i32, ptr %c.addr
  %t12 = add i32 %t11, 1
  store i32 %t12, ptr %c.addr
  br label %endif3
else3:
  ; else
  ; set b
  %t13 = load i32, ptr %b.addr
  %t14 = add i32 %t13, 5
  store i32 %t14, ptr %b.addr
  br label %endif3
endif3:
  br label %endif2
else2:
  ; else
  ; set c
  %t15 = load i32, ptr %c.addr
  %t16 = add i32 %t15, 4
  store i32 %t16, ptr %c.addr
  br label %endif2
endif2:
  br label %endif1
else1:
  ; else
  ; if condition
  %t17 = srem i32 %i.phi0, 2
  %t18 = icmp eq i32 %t17, 0
  br i1 %t18, label %then4, label %endif4
then4:
  ; then
  ; set a
  %t19 = load i32, ptr %a.addr
  %t20 = add i32 %t19, 1
  store i32 %t20, ptr %a.addr
  br label %endif4
endif4:
  br label %endif1
endif1:
  ; set i
  %i.next0 = add i32 %i.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %i.phi0, ptr %i.addr
  br label %while.end
while.end:
  ; return
  %t21 = load i32, ptr %a.addr
  %t22 = load i32, ptr %b.addr
  %t23 = add i32 %t21, %t22
  %t24 = load i32, ptr %c.addr
  %t25 = add i32 %t23, %t24
  ret i32 %t25
}

