; generated by weavec
; source: test/performance/wir/0133_sieve48_i32.wir
; core-version: 3

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %.t0 = call ptr @malloc(i64 196)
  ; let flags
  ; if condition
  %.t1 = icmp eq ptr %.t0, null
  br i1 %.t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %.t2 = call i32 @count_primes48(ptr %.t0)
  ; let n
  call void @free(ptr %.t0)
  ; return
  ret i32 %.t2
}

; function: flag_ptr
; params: ptr, i32
; returns: ptr
define ptr @flag_ptr(ptr %flags, i32 %idx) {
entry:
  ; return
  %.t0 = sext i32 %idx to i64
  %.t1 = getelementptr i32, ptr %flags, i64 %.t0
  ret ptr %.t1
}

; function: count_primes48
; params: ptr
; returns: i32
define i32 @count_primes48(ptr %flags) {
entry:
  %i.addr = alloca i32
  %p.addr = alloca i32
  %j.addr = alloca i32
  %k.addr = alloca i32
  %count.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %.t0 = load i32, ptr %i.addr
  %.t1 = icmp sle i32 %.t0, 48
  br i1 %.t1, label %while.body, label %while.end
while.body:
  ; while body
  %.t2 = load i32, ptr %i.addr
  %.t3 = call ptr @flag_ptr(ptr %flags, i32 %.t2)
  store i32 1, ptr %.t3
  ; set i
  %.t4 = load i32, ptr %i.addr
  %.t5 = add i32 %.t4, 1
  store i32 %.t5, ptr %i.addr
  br label %while.cond
while.end:
  %.t6 = call ptr @flag_ptr(ptr %flags, i32 0)
  store i32 0, ptr %.t6
  %.t7 = call ptr @flag_ptr(ptr %flags, i32 1)
  store i32 0, ptr %.t7
  ; let p
  store i32 2, ptr %p.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %.t8 = load i32, ptr %p.addr
  %.t9 = load i32, ptr %p.addr
  %.t10 = mul i32 %.t8, %.t9
  %.t11 = icmp sle i32 %.t10, 48
  br i1 %.t11, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; if condition
  %.t12 = load i32, ptr %p.addr
  %.t13 = call ptr @flag_ptr(ptr %flags, i32 %.t12)
  %.t14 = load i32, ptr %.t13
  %.t15 = icmp ne i32 %.t14, 0
  br i1 %.t15, label %then2, label %endif2
then2:
  ; then
  %.t16 = load i32, ptr %p.addr
  %.t17 = load i32, ptr %p.addr
  %.t18 = mul i32 %.t16, %.t17
  ; let m
  ; let j
  store i32 %.t18, ptr %j.addr
  ; while condition
  br label %while.cond3
while.cond3:
  %.t19 = load i32, ptr %j.addr
  %.t20 = icmp sle i32 %.t19, 48
  br i1 %.t20, label %while.body3, label %while.end3
while.body3:
  ; while body
  %.t21 = load i32, ptr %j.addr
  %.t22 = call ptr @flag_ptr(ptr %flags, i32 %.t21)
  store i32 0, ptr %.t22
  ; set j
  %.t23 = load i32, ptr %j.addr
  %.t24 = load i32, ptr %p.addr
  %.t25 = add i32 %.t23, %.t24
  store i32 %.t25, ptr %j.addr
  br label %while.cond3
while.end3:
  br label %endif2
endif2:
  ; set p
  %.t26 = load i32, ptr %p.addr
  %.t27 = add i32 %.t26, 1
  store i32 %.t27, ptr %p.addr
  br label %while.cond1
while.end1:
  ; let k
  store i32 0, ptr %k.addr
  ; let count
  store i32 0, ptr %count.addr
  ; while condition
  br label %while.cond4
while.cond4:
  %.t28 = load i32, ptr %k.addr
  %.t29 = icmp sle i32 %.t28, 48
  br i1 %.t29, label %while.body4, label %while.end4
while.body4:
  ; while body
  ; if condition
  %.t30 = load i32, ptr %k.addr
  %.t31 = call ptr @flag_ptr(ptr %flags, i32 %.t30)
  %.t32 = load i32, ptr %.t31
  %.t33 = icmp ne i32 %.t32, 0
  br i1 %.t33, label %then5, label %endif5
then5:
  ; then
  ; set count
  %.t34 = load i32, ptr %count.addr
  %.t35 = add i32 %.t34, 1
  store i32 %.t35, ptr %count.addr
  br label %endif5
endif5:
  ; set k
  %.t36 = load i32, ptr %k.addr
  %.t37 = add i32 %.t36, 1
  store i32 %.t37, ptr %k.addr
  br label %while.cond4
while.end4:
  ; return
  %.t38 = load i32, ptr %count.addr
  ret i32 %.t38
}

