; generated by weavec2
; source: test/performance/wir/0137_mandelbrot_grid6_sum_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i32 @grid_sum()
  ret i32 %t0
}

; function: escape_count
; params: i32, i32, i32
; returns: i32
define i32 @escape_count(i32 %cx, i32 %cy, i32 %max_iter) {
entry:
  %zx.addr = alloca i32
  %zy.addr = alloca i32
  %iter.addr = alloca i32
  %active.addr = alloca i32
  ; let zx
  store i32 0, ptr %zx.addr
  ; let zy
  store i32 0, ptr %zy.addr
  ; let iter
  store i32 0, ptr %iter.addr
  ; let active
  store i32 1, ptr %active.addr
  ; while condition
  br label %while.pre
while.pre:
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %iter.addr
  %t1 = icmp slt i32 %t0, %max_iter
  %t2 = load i32, ptr %active.addr
  %t3 = icmp ne i32 %t2, 0
  %t4 = and i1 %t1, %t3
  br i1 %t4, label %while.body, label %while.exit-merge
while.body:
  ; while body
  %t5 = load i32, ptr %zx.addr
  %t6 = load i32, ptr %zx.addr
  %t7 = mul i32 %t5, %t6
  %t8 = sdiv i32 %t7, 1000
  ; let zx2
  %t9 = load i32, ptr %zy.addr
  %t10 = load i32, ptr %zy.addr
  %t11 = mul i32 %t9, %t10
  %t12 = sdiv i32 %t11, 1000
  ; let zy2
  %t13 = add i32 %t8, %t12
  ; let radius2
  ; if condition
  %t14 = icmp sgt i32 %t13, 4000
  br i1 %t14, label %then1, label %else1
then1:
  ; then
  ; set active
  store i32 0, ptr %active.addr
  br label %endif1
else1:
  ; else
  %t15 = load i32, ptr %zx.addr
  %t16 = mul i32 2, %t15
  %t17 = load i32, ptr %zy.addr
  %t18 = mul i32 %t16, %t17
  %t19 = sdiv i32 %t18, 1000
  ; let two_zx_zy
  ; set zy
  %t20 = add i32 %t19, %cy
  store i32 %t20, ptr %zy.addr
  ; set zx
  %t21 = sub i32 %t8, %t12
  %t22 = add i32 %t21, %cx
  store i32 %t22, ptr %zx.addr
  ; set iter
  %t23 = load i32, ptr %iter.addr
  %t24 = add i32 %t23, 1
  store i32 %t24, ptr %iter.addr
  br label %endif1
endif1:
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  br label %while.end
while.end:
  ; return
  %t25 = load i32, ptr %iter.addr
  ret i32 %t25
}

; function: grid_sum
; params: none
; returns: i32
define i32 @grid_sum() {
entry:
  %py.addr = alloca i32
  %total.addr = alloca i32
  %px.addr = alloca i32
  ; let py
  store i32 0, ptr %py.addr
  ; let total
  store i32 0, ptr %total.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %py.addr
  %t1 = icmp slt i32 %t0, 6
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; let px
  store i32 0, ptr %px.addr
  ; while condition
  br label %while.pre1
while.pre1:
  %total.init1 = load i32, ptr %total.addr
  %px.init1 = load i32, ptr %px.addr
  br label %while.cond1
while.cond1:
  %total.phi1 = phi i32 [%total.init1, %while.pre1], [%total.next1, %while.latch1]
  %px.phi1 = phi i32 [%px.init1, %while.pre1], [%px.next1, %while.latch1]
  %t2 = icmp slt i32 %px.phi1, 6
  br i1 %t2, label %while.body1, label %while.exit-merge1
while.body1:
  ; while body
  %t3 = mul i32 %px.phi1, 500
  %t4 = sub i32 %t3, 1500
  ; let cx
  %t5 = load i32, ptr %py.addr
  %t6 = mul i32 %t5, 500
  %t7 = sub i32 %t6, 1500
  ; let cy
  ; let esc (deferred)
  ; set total
  %t8 = call i32 @escape_count(i32 %t4, i32 %t7, i32 32)
  %total.next1 = add i32 %total.phi1, %t8
  ; set px
  %px.next1 = add i32 %px.phi1, 1
  br label %while.latch1
while.latch1:
  br label %while.cond1
while.exit-merge1:
  ; sync loop-carried locals to stack
  store i32 %total.phi1, ptr %total.addr
  store i32 %px.phi1, ptr %px.addr
  br label %while.end1
while.end1:
  ; set py
  %t9 = load i32, ptr %py.addr
  %t10 = add i32 %t9, 1
  store i32 %t10, ptr %py.addr
  br label %while.cond
while.end:
  ; return
  %t11 = load i32, ptr %total.addr
  ret i32 %t11
}

