; generated by weavec
; source: test/performance/wir/0147_partition_dutch12_i32.wir
; core-version: 2

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 48)
  ; let a
  ; if condition
  %t1 = icmp eq ptr %t0, null
  br i1 %t1, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t2 = call ptr @elem(ptr %t0, i32 0)
  store i32 2, ptr %t2
  %t3 = call ptr @elem(ptr %t0, i32 1)
  store i32 0, ptr %t3
  %t4 = call ptr @elem(ptr %t0, i32 2)
  store i32 1, ptr %t4
  %t5 = call ptr @elem(ptr %t0, i32 3)
  store i32 2, ptr %t5
  %t6 = call ptr @elem(ptr %t0, i32 4)
  store i32 0, ptr %t6
  %t7 = call ptr @elem(ptr %t0, i32 5)
  store i32 1, ptr %t7
  %t8 = call ptr @elem(ptr %t0, i32 6)
  store i32 2, ptr %t8
  %t9 = call ptr @elem(ptr %t0, i32 7)
  store i32 0, ptr %t9
  %t10 = call ptr @elem(ptr %t0, i32 8)
  store i32 1, ptr %t10
  %t11 = call ptr @elem(ptr %t0, i32 9)
  store i32 2, ptr %t11
  %t12 = call ptr @elem(ptr %t0, i32 10)
  store i32 0, ptr %t12
  %t13 = call ptr @elem(ptr %t0, i32 11)
  store i32 1, ptr %t13
  %t14 = call i32 @partition012(ptr %t0)
  ; let zeros
  call void @free(ptr %t0)
  ; return
  ret i32 %t14
}

; function: elem
; params: ptr, i32
; returns: ptr
define ptr @elem(ptr %a, i32 %idx) {
entry:
  ; return
  %t0 = sext i32 %idx to i64
  %t1 = getelementptr i32, ptr %a, i64 %t0
  ret ptr %t1
}

; function: partition012
; params: ptr
; returns: i32
define i32 @partition012(ptr %a) {
entry:
  %lo.addr = alloca i32
  %mid.addr = alloca i32
  %hi.addr = alloca i32
  ; let lo
  store i32 0, ptr %lo.addr
  ; let mid
  store i32 0, ptr %mid.addr
  ; let hi
  store i32 11, ptr %hi.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %mid.addr
  %t1 = load i32, ptr %hi.addr
  %t2 = icmp sle i32 %t0, %t1
  br i1 %t2, label %while.body, label %while.end
while.body:
  ; while body
  %t3 = load i32, ptr %mid.addr
  %t4 = call ptr @elem(ptr %a, i32 %t3)
  %t5 = load i32, ptr %t4
  ; let v
  ; if condition
  %t6 = icmp eq i32 %t5, 0
  br i1 %t6, label %then1, label %else1
then1:
  ; then
  %t7 = load i32, ptr %lo.addr
  %t8 = call ptr @elem(ptr %a, i32 %t7)
  %t9 = load i32, ptr %t8
  ; let tmp
  %t10 = load i32, ptr %lo.addr
  %t11 = call ptr @elem(ptr %a, i32 %t10)
  store i32 %t5, ptr %t11
  %t12 = load i32, ptr %mid.addr
  %t13 = call ptr @elem(ptr %a, i32 %t12)
  store i32 %t9, ptr %t13
  ; set lo
  %t14 = load i32, ptr %lo.addr
  %t15 = add i32 %t14, 1
  store i32 %t15, ptr %lo.addr
  ; set mid
  %t16 = load i32, ptr %mid.addr
  %t17 = add i32 %t16, 1
  store i32 %t17, ptr %mid.addr
  br label %endif1
else1:
  ; else
  ; if condition
  %t18 = icmp eq i32 %t5, 2
  br i1 %t18, label %then2, label %else2
then2:
  ; then
  %t19 = load i32, ptr %hi.addr
  %t20 = call ptr @elem(ptr %a, i32 %t19)
  %t21 = load i32, ptr %t20
  ; let tmp2
  %t22 = load i32, ptr %hi.addr
  %t23 = call ptr @elem(ptr %a, i32 %t22)
  store i32 %t5, ptr %t23
  %t24 = load i32, ptr %mid.addr
  %t25 = call ptr @elem(ptr %a, i32 %t24)
  store i32 %t21, ptr %t25
  ; set hi
  %t26 = load i32, ptr %hi.addr
  %t27 = sub i32 %t26, 1
  store i32 %t27, ptr %hi.addr
  br label %endif2
else2:
  ; else
  ; set mid
  %t28 = load i32, ptr %mid.addr
  %t29 = add i32 %t28, 1
  store i32 %t29, ptr %mid.addr
  br label %endif2
endif2:
  br label %endif1
endif1:
  br label %while.cond
while.end:
  ; return
  %t30 = load i32, ptr %lo.addr
  ret i32 %t30
}

