; generated by weavec
; source: test/performance/wir/0152_merge_sorted_halves8_i32.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 16)
  ; let left
  %t1 = call ptr @malloc(i64 16)
  ; let right
  %t2 = call ptr @malloc(i64 32)
  ; let out
  ; if condition
  %t3 = icmp eq ptr %t0, null
  %t4 = icmp eq ptr %t1, null
  %t5 = icmp eq ptr %t2, null
  %t6 = or i1 %t4, %t5
  %t7 = or i1 %t3, %t6
  br i1 %t7, label %then, label %endif
then:
  ; then
  ; return
  ret i32 0
endif:
  %t8 = call ptr @elem(ptr %t0, i32 0)
  store i32 1, ptr %t8
  %t9 = call ptr @elem(ptr %t0, i32 1)
  store i32 5, ptr %t9
  %t10 = call ptr @elem(ptr %t0, i32 2)
  store i32 9, ptr %t10
  %t11 = call ptr @elem(ptr %t0, i32 3)
  store i32 13, ptr %t11
  %t12 = call ptr @elem(ptr %t1, i32 0)
  store i32 2, ptr %t12
  %t13 = call ptr @elem(ptr %t1, i32 1)
  store i32 6, ptr %t13
  %t14 = call ptr @elem(ptr %t1, i32 2)
  store i32 10, ptr %t14
  %t15 = call ptr @elem(ptr %t1, i32 3)
  store i32 14, ptr %t15
  %t16 = call i32 @merge8(ptr %t0, ptr %t1, ptr %t2)
  ; let sum
  call void @free(ptr %t0)
  call void @free(ptr %t1)
  call void @free(ptr %t2)
  ; return
  ret i32 %t16
}

; function: elem
; params: ptr, i32
; returns: ptr
define ptr @elem(ptr %a, i32 %idx) {
entry:
  ; return
  %t0 = sext i32 %idx to i64
  %t1 = getelementptr i32, ptr %a, i64 %t0
  ret ptr %t1
}

; function: merge8
; params: ptr, ptr, ptr
; returns: i32
define i32 @merge8(ptr %left, ptr %right, ptr %out) {
entry:
  %i.addr = alloca i32
  %j.addr = alloca i32
  %k.addr = alloca i32
  %checksum.addr = alloca i32
  ; let i
  store i32 0, ptr %i.addr
  ; let j
  store i32 0, ptr %j.addr
  ; let k
  store i32 0, ptr %k.addr
  ; let checksum
  store i32 0, ptr %checksum.addr
  ; while condition
  br label %while.pre
while.pre:
  %k.init0 = load i32, ptr %k.addr
  br label %while.cond
while.cond:
  %k.phi0 = phi i32 [%k.init0, %while.pre], [%k.next0, %while.latch]
  %t0 = icmp slt i32 %k.phi0, 8
  br i1 %t0, label %while.body, label %while.exit-merge
while.body:
  ; while body
  ; if condition
  %t1 = load i32, ptr %i.addr
  %t2 = icmp slt i32 %t1, 4
  %t3 = load i32, ptr %j.addr
  %t4 = icmp sge i32 %t3, 4
  %t5 = load i32, ptr %i.addr
  %t6 = call ptr @elem(ptr %left, i32 %t5)
  %t7 = load i32, ptr %t6
  %t8 = load i32, ptr %j.addr
  %t9 = call ptr @elem(ptr %right, i32 %t8)
  %t10 = load i32, ptr %t9
  %t11 = icmp sle i32 %t7, %t10
  %t12 = or i1 %t4, %t11
  %t13 = and i1 %t2, %t12
  br i1 %t13, label %then1, label %else1
then1:
  ; then
  %t14 = load i32, ptr %i.addr
  %t15 = call ptr @elem(ptr %left, i32 %t14)
  %t16 = load i32, ptr %t15
  ; let v
  %t17 = call ptr @elem(ptr %out, i32 %k.phi0)
  store i32 %t16, ptr %t17
  ; set checksum
  %t18 = load i32, ptr %checksum.addr
  %t19 = add i32 %t18, %t16
  store i32 %t19, ptr %checksum.addr
  ; set i
  %t20 = load i32, ptr %i.addr
  %t21 = add i32 %t20, 1
  store i32 %t21, ptr %i.addr
  br label %endif1
else1:
  ; else
  %t22 = load i32, ptr %j.addr
  %t23 = call ptr @elem(ptr %right, i32 %t22)
  %t24 = load i32, ptr %t23
  ; let w
  %t25 = call ptr @elem(ptr %out, i32 %k.phi0)
  store i32 %t24, ptr %t25
  ; set checksum
  %t26 = load i32, ptr %checksum.addr
  %t27 = add i32 %t26, %t24
  store i32 %t27, ptr %checksum.addr
  ; set j
  %t28 = load i32, ptr %j.addr
  %t29 = add i32 %t28, 1
  store i32 %t29, ptr %j.addr
  br label %endif1
endif1:
  ; set k
  %k.next0 = add i32 %k.phi0, 1
  br label %while.latch
while.latch:
  br label %while.cond
while.exit-merge:
  ; sync loop-carried locals to stack
  store i32 %k.phi0, ptr %k.addr
  br label %while.end
while.end:
  ; return
  %t30 = load i32, ptr %checksum.addr
  ret i32 %t30
}

