; generated by weavec
; source: test/performance/wir/0153_sum_range_i64.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %i.addr = alloca i32
  %acc.addr = alloca i64
  ; let i
  store i32 1, ptr %i.addr
  ; let acc
  store i64 0, ptr %acc.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp sle i32 %t0, 120
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set acc
  %t2 = load i64, ptr %acc.addr
  %t3 = load i32, ptr %i.addr
  %t4 = sext i32 %t3 to i64
  %t5 = add i64 %t2, %t4
  store i64 %t5, ptr %acc.addr
  ; set i
  %t6 = load i32, ptr %i.addr
  %t7 = add i32 %t6, 1
  store i32 %t7, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t8 = load i64, ptr %acc.addr
  %t9 = trunc i64 %t8 to i32
  ret i32 %t9
}

