; generated by weavec
; source: test/performance/wir/0162_bitwise_mix_i64.wir
; core-version: 3

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t0 = call i64 @mix64(i64 0)
  %t1 = srem i64 %t0, 1000000007
  %t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

; function: mix64
; params: i64
; returns: i64
define i64 @mix64(i64 %seed) {
entry:
  %x.addr = alloca i64
  %i.addr = alloca i32
  ; let x
  store i64 %seed, ptr %x.addr
  ; let i
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond
while.cond:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, 64
  br i1 %t1, label %while.body, label %while.end
while.body:
  ; while body
  ; set x
  %t2 = load i64, ptr %x.addr
  %t3 = and i64 %t2, 255
  %t4 = shl i64 %t3, 3
  %t5 = load i64, ptr %x.addr
  %t6 = ashr i64 %t5, 5
  %t7 = xor i64 %t4, %t6
  store i64 %t7, ptr %x.addr
  ; set i
  %t8 = load i32, ptr %i.addr
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %i.addr
  br label %while.cond
while.end:
  ; return
  %t10 = load i64, ptr %x.addr
  ret i64 %t10
}

