# SPDX-License-Identifier: Apache-2.0
name: checkout-export

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: checkout-${{ github.sha }}
          path: |
            .github
            docs
            runtime
            scripts
            src
            test
            .gitignore
            CHANGELOG.md
            LICENSE
            README.md
            VERSION
            build.sh
            selfhost.sh
            test-all.sh
            test.sh
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1
